steps:
  # Build the container image for the server
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'gcr.io/$PROJECT_ID/foundry-proxy-server'
      - '-f'
      - 'server/Dockerfile'
      - '.'
  
  # Push the container image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/foundry-proxy-server']
  
  # Deploy container image to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'foundry-proxy-server'
      - '--image'
      - 'gcr.io/$PROJECT_ID/foundry-proxy-server'
      - '--region'
      - 'us-central1'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--port'
      - '3000'

images:
  - 'gcr.io/$PROJECT_ID/foundry-proxy-server'